### ISSUE TITLE
PyMiniRacer having issues on Windows

### ISSUE THREAD

**Issue by reteps** [sqreen/PyMiniRacer#85]
### Actual behavior
Tell us what happens instead
+ `FileNotFoundError: [WinError 2] The specified file was not found`
+ See full logs under [this issue](https://github.com/reteps/kbot/issues/14).
### System configuration

**Python version**:
3.6.5
**Pip version**:
19.2.2

@danielkp1234

**Comment by nizox** [comment]
There is currently no wheel built for Windows. The error reported by your user is because the module was trying to compile v8 from source and it requires a few tools like `git` and also probably a compiler.

**Comment by danielkp1234** [comment]
@nizox wait so how would i get a wheel that supports windows 10?

**Comment by danielkp1234** [comment]
@nizox is there a wheel for windows 10

**Comment by danielkp1234** [comment]
@sqreen

**Comment by nizox** [comment]
Hello @danielkp1234,

We have been working on adding support for Windows to PyMiniRacer. This was a huge work because it required to upgrade the V8 release branch to 7.8 and patch the extension.

The work was carried on https://github.com/sqreen/PyMiniRacer/pull/89. You will soon be able to test the Windows support with the dev wheels that should be made available by the CI [here](https://dev.azure.com/sqreenci/PyMiniRacer/_build/results?buildId=1266&view=results).

**Comment by nizox** [comment]
The last beta version of PyMiniRacer brings support for Windows (https://pypi.org/project/py-mini-racer/0.2.0b2/). You can install it using the following command:
```
pip install --pre py-mini-racer
```
